[package]
name = "room-matcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
common_macros = "0.1.1"
rand = "0.8.5"
toml = "0.7.3"
