[config]
solutions = 5000

[1]
preferred = ["2", "3", "5", "7"]
unpreferred = ["4", "8"]

[2]
preferred = ["1", "5", "8", "4"]
unpreferred = ["3"]

[3]
preferred = ["1", "4", "7", "8"]
unpreferred = ["5", "6"]

[4]
preferred = ["2", "5", "8"]
unpreferred = ["6"]

[5]
preferred = ["1", "4", "7", "8"]
unpreferred = ["2"]

[6]
preferred = ["3", "7", "8"]
unpreferred = ["2", "5"]

[7]
preferred = ["3", "6"]
unpreferred = [""]

[8]
preferred = []
unpreferred = []
